=pod

=head1 NAME

check_esx_datatore.pl

=head1 SYNOPSYS

check_esx_datastore.pl -H <hostname> -u <root> -p <password> -w <warning> -c <critical>

=head1 DESCRIPTION

check_esx_dataore.pl is an Nagios-Plugin checking the freespace of the Datatores of an vCenter or ESX(i).

=head1 OPTIONS

-H 
Hostname or IP-Address of a vCenter or ESX(i). (required)

-u 
Username (required)

-p
Password (required)

-w
Treshhold (Free Space in Percent) for warnings (INTEGER) (required)

-c
Treshhold (Free Space in Percent) for critical (INTEGER) (required)

=head1 FILES

check_esx_datastore.pl

=head1 AUTHOR

Torge Gipp torge<at>tg432<dot>de

=cut